### ISSUE TITLE
The search results does not disappear after search is completed

### ISSUE THREAD

**Issue by lambasl** [The-Giving-Tree/client-react#1]
On searching for a search term in the search bar, the results are displayed in drop down. On selecting the result the searched results should disappear. The results stay there even when clicking outside the search area.

![Screen Shot 2020-03-24 at 3 47 39 PM](https://user-images.githubusercontent.com/14056014/77484167-12e39880-6de7-11ea-9162-7b074f431918.png)

**Steps to reproduce:**

1. Type in a search term
2. From the search results displayed select one of them
3. Click anywhere else on the page except on search results.

MacOS version : 10.14.6
Google Chrome Version 80.0.3987.132

Same for safari
Safari Version 12.1.2 (14607.3.9)

This can be a separate bug but the  header appears distorted in safari.

![Screen Shot 2020-03-24 at 3 54 31 PM](https://user-images.githubusercontent.com/14056014/77484439-c51b6000-6de7-11ea-9ae2-c0647731374c.png)

**Comment by nomaxg** [comment]
I can take a stab at this one

**Comment by gmaijoe** [comment]
👍
