### ISSUE TITLE
Adding side bar (to all pages globally)

### ISSUE THREAD

**Issue by gmaijoe** [The-Giving-Tree/client-react#2]
Currently the side bar is only present on the /home/discover route.

Example:
<img width="1680" alt="Screen Shot 2020-03-24 at 7 20 28 PM" src="https://user-images.githubusercontent.com/7184919/77495030-b000fa00-6e04-11ea-98c6-3454edbf463e.png">

would be great to see it be present on all pages.
Example:
<img width="1680" alt="Screen Shot 2020-03-24 at 7 20 39 PM" src="https://user-images.githubusercontent.com/7184919/77495047-b8593500-6e04-11ea-8592-771782ad90b3.png">

**Comment by gflujan** [comment]
@gmaijoe I can take this one on.

**Comment by gmaijoe** [comment]
👍

**Comment by gflujan** [comment]
@gmaijoe Alright, I've added the sidebar to all of the pages except for the settings page. It didn't seem right to put it there. :-) But if you think it should be added, I can put it there as well.

Overall, I put all of the work on a branch called `ISSUE_NUM_2`. Please take a look and let me know what you think.

**Comment by gflujan** [comment]
I just realized that the `Post` page could use the sidebar. I'll see if I can get to it tomorrow night, if not, I can take a look at it on Friday night.

**Comment by gflujan** [comment]
@gmaijoe alright, I added the sidebar to post comments view. do you want to take a look at the changes in a pull request before I merge them in?

**Comment by gmaijoe** [comment]
sure! looking rn

**Comment by gmaijoe** [comment]
check out my PR: https://github.com/The-Giving-Tree/client-react/pull/13

i merged new stuff from master in - it looks good to me rn

**Comment by gflujan** [comment]
Cool, yea everything looks good on that PR. if you don't mind, would you be able to merge it in?

**Comment by gflujan** [comment]
Closing this now that this branch has been merged into `master`.
