### ISSUE TITLE
UpVote / Downvote doesn't happen in real time

### ISSUE THREAD

**Issue by gmaijoe** [The-Giving-Tree/client-react#3]
This has long been an issue but I'm not sure what the best way to fix it is.

https://gfycat.com/fearfulvigilantchinesecrocodilelizard

The reason why it's a bit tricky is that the newsfeed upvotes and downvotes are being sent from the backend. The client renders only what is explicitly sent from the backend.

So an upvote on the page needs to propagate to the backend and then the client would need to reload, which could mess up the page's position.

A short term solution could be to artificially upvote or downvote a certain request on the client side, without re-pulling the newsfeed.

So even though the newsfeed says Upvote = 2, If i upvote on the front end, I just add 1 to 2, equaling 3.

**Comment by shuklavk** [comment]
I can try this one.

**Comment by gmaijoe** [comment]
I ended up fixing this. the way I solved this was using index Arrays to keep track of local upvotes and downvotes. then summing the upvotes and downvotes with the backend DB. works like a charm. here's the PR:

https://github.com/The-Giving-Tree/client-react/pull/6
