### ISSUE TITLE
background color doesn't extend full height of page

### ISSUE THREAD

**Issue by gmaijoe** [The-Giving-Tree/client-react#4]
<img width="1680" alt="Screen Shot 2020-03-24 at 10 18 08 PM" src="https://user-images.githubusercontent.com/7184919/77504382-6670d900-6e1d-11ea-819f-f6fd6e9919dc.png">

see gray and white divide lol - this happens when the page is taller

**Comment by gflujan** [comment]
I'm not sure if the work I did in branch `ISSUE_NUM_2` fixed this, but I don't see any white space at the bottom.

**Comment by gmaijoe** [comment]
<img width="1680" alt="Screen Shot 2020-03-26 at 3 22 21 PM" src="https://user-images.githubusercontent.com/7184919/77702376-9b903f00-6f75-11ea-9433-1c35426ba31d.png">

i still got the issue on this page: http://localhost:3001/home/global

**Comment by gmaijoe** [comment]
<img width="1680" alt="Screen Shot 2020-03-26 at 3 27 08 PM" src="https://user-images.githubusercontent.com/7184919/77702666-499be900-6f76-11ea-92df-dbaabb4d0481.png">

also prominent white space in the profile page

**Comment by gflujan** [comment]
what branch is this on?

**Comment by gmaijoe** [comment]
this is on your branch `ISSUE_NUM_2`

**Comment by gflujan** [comment]
ok, gotcha. just for my info, what resolution screen are you on?

**Comment by gmaijoe** [comment]
using white bg now
